Fix loading factories in extensions after the last changes in Solidus
solidusio/solidus_dev_support pull request #169
Opened 2021-02-17 12:17 UTC by kennyadsl

## Summary

This PR reflects the last changes we made in Solidus to support the new FactoryBot loading mechanism. 

We need to merge and release new versions of Solidus after https://github.com/solidusio/solidus/pull/3907, merge this PR and release a new version of `solidus_dev_support` to have the ecosystem working again with factories.  

When testing extensions using Solidus versions that support the `definition_file_paths`, it will load the core factory first
and then the ones defined in `lib/extension_name/testing_support/factories`. 

If the extension has a `lib/extension_name/testing_support/factories.rb` file that loads all the factories into `lib/extension_name/testing_support/factories/`, it should be removed now. If that happens this PR will make it print a deprecation warning telling users what to do. 

## Checklist

- [x] I have structured the commits for clarity and conciseness.
- ~[ ] I have added relevant automated tests for this change.~

2021-02-17 12:20 UTC, kennyadsl commented
Specs failures are legit, until we merge the PR on Solidus mentioned above.

2021-02-18 02:11 UTC, jarednorman requested changes

2021-02-18 02:11 UTC, jarednorman commented on lib/solidus_dev_support/testing_support/factories.rb
> +        if using_factory_bot_deinition_file_paths?
```suggestion
        if using_factory_bot_definition_file_paths?
```

2021-02-18 20:33 UTC, kennyadsl commented on lib/solidus_dev_support/testing_support/factories.rb
> +        if using_factory_bot_deinition_file_paths?
Thank you @jarednorman!

2021-02-18 21:54 UTC, jarednorman approved these changes

2021-02-18 21:55 UTC, merged

2021-02-18 21:59 UTC, jarednorman commented
I didn't expect that. 🤔

2021-02-18 22:00 UTC, kennyadsl commented
No problem, this gem is mainly used from Rubygems so it does nothing until we release a new version, which is actually how all the other gems should work as well. 😬