Add instruction on how to use the new factories in apps
solidusio/solidus_dev_support pull request #172
Opened 2021-02-20 12:12 UTC by kennyadsl

To load factories of extensions.

2021-02-20 15:45 UTC, aldesantis reviewed
I'm not sure the explanation here is very meaningful for end users. What does it mean exactly for someone to use `FactoryBot.definition_file_paths`?

2021-02-20 17:19 UTC, kennyadsl commented
Yes, I know this could be confusing. It means that in the `spec_helper` of your host application you may have switched to the new [FactoryBot automatic loading](https://github.com/thoughtbot/factory_bot_rails#automatic-factory-definition-loading) using `FactoryBot.definition_file_paths`. Right now we can't use that API directory to load extensions factory, unless we do something like:

```ruby
FactoryBot.definition_file_paths = [
  Spree::TestingSupport::FactoryBot.definition_file_paths,
  SolidusSubscriptions::Engine.root.glob('lib/solidus_subscriptions/testing_support/factories/**/*_factory.rb').map { |path| path.sub(/.rb\z/, '') },
  Rails.root.join('spec/factories')
].flatten
```

So, we can take advantage of this method added into `solidus_dev_support`, that also loads core factories:

```ruby
SolidusDevSupport::TestingSupport::Factories.load_for(SolidusSubscription::Engine, SolidusContent::Engine)
```

This is an intermediate step, I'd like the final API in a host application to be:

```ruby
FactoryBot.definition_file_paths = [
  Spree::TestingSupport::FactoryBot.definition_file_paths,
  SolidusSubscriptions::FactoryBot.definition_file_paths,
  Rails.root.join('spec/factories')
].flatten
```

2021-02-22 08:20 UTC, aldesantis requested changes
@kennyadsl thanks for explanation, there's a quick typo that needs to be fixed but good to go otherwise. I'm not approving because Mergify would merge it. 😅

2021-02-22 08:20 UTC, aldesantis commented on lib/solidus_dev_support/templates/extension/README.md
> +factories along with this extensions factories with this statement:
Should be "extension's factories".

2021-02-22 11:21 UTC, kennyadsl commented on lib/solidus_dev_support/templates/extension/README.md
> +factories along with this extensions factories with this statement:
Done, thanks for the review!

2021-02-22 17:34 UTC, aldesantis approved these changes

2021-02-22 17:35 UTC, merged